modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory
issueTrackerURL="http://my.issue.tracker/" #optional
license="ARR"

[[mods]]
	modId="projectbrazier"
	version="${version}"
	displayName="Project Brazier"
	#updateJSONURL="https://dark-roleplay.net/files/versions/drpmedieval/drpmedieval-1.13.2.json" #optional
	displayURL="https://dark-roleplay.net/"
	logoFile="project_brazier_logo.png" #optional
	credits="\nDeveloper Team:\nJTK222, 0Mr_X0\n Artists:\nRolfaal & Kanno (https://twitter.com/lKanno_)\n Beta Testers:\nDunkelzwerg11, BluryFace, Lord Kittin, 0Mr_X0"
	authors=["JTK222", "0Mr_X0", "Rolfaal", "Kanno"]
	description='''Project Brazier is the continuation of the Dark Roleplay Medieval mod.'''
	itemIcon="projectbrazier:iron_brazier_coal"

[modproperties.projectbrazier]
    margMaterialFiles=[
        "fixed_data/projectbrazier/materials/apple.json",
        "fixed_data/projectbrazier/materials/orange.json",
    ]
	hasMargDatas=true
	hasMargAssets=true

dependencies.projectbrazier = [
	{modid="forge", mandatory=true, versionRange="[36,)", ordering="NONE",side="BOTH"},
	{modid="marg", mandatory=true, versionRange="[1.16.5-0.6,)", ordering="AFTER",side="BOTH"}
]


