modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory
issueTrackerURL="https://github.com/DarkRoleplay/Project-Brazier/issues" #optional
license="ARR"

[[mods]]
	modId="projectbrazier"
	version="0.6.1"
	displayName="Project Brazier"
	#updateJSONURL="https://dark-roleplay.net/files/versions/drpmedieval/drpmedieval-1.13.2.json" #optional
	displayURL="https://www.curseforge.com/minecraft/mc-mods/project-brazier"
	logoFile="project_brazier_logo.png" #optional
	credits="""
		Developer Team:\
		JTK222, 0Mr_X0\
		Artists:\
		Rolfaal & Kanno (https://twitter.com/lKanno_)\
		Beta Testers:\
		Dunkelzwerg11, BluryFace, Lord Kittin, 0Mr_X0
		"""
	authors=["JTK222", "0Mr_X0", "Rolfaal", "Kanno"]
	description='''Project Brazier is the continuation of the Dark Roleplay Medieval mod.'''
	itemIcon="projectbrazier:iron_brazier_coal"

[modproperties.projectbrazier]
    margMaterialFiles=[
        "fixed_data/projectbrazier/materials/apple.json",
        "fixed_data/projectbrazier/materials/orange.json",
    ]
	hasMargDatas=true
	hasMargAssets=true

dependencies.projectbrazier = [
	{modid="forge", mandatory=true, versionRange="[38.0.17,)", ordering="NONE",side="BOTH"},
	{modid="marg", mandatory=true, versionRange="[1.18-0.7.1,)", ordering="AFTER",side="BOTH"}
]


